const { chromium } = require('playwright');
(async()=>{const b=await chromium.launch();const errs=[];const p=await b.newPage({viewport:{width:1300,height:950}});
p.on('pageerror',e=>errs.push('PE '+e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
await p.goto('http://127.0.0.1:47831/'); await p.waitForSelector('#boot',{state:'hidden',timeout:30000}); if(await p.isVisible('#newsok')) await p.click('#newsok');
await p.click('#syncpill'); await p.waitForTimeout(4000);
await p.click('#t-portals'); await p.waitForTimeout(300);
console.log('places visible', await p.isVisible('#gplacecard'), await p.textContent('#gplacenote'));
console.log((await p.$$eval('#gplaces .srow', a=>a.slice(0,4).map(x=>x.innerText.replace(/\s+/g,' ')))).join('\n'));
await p.click('[data-pl="0"]'); await p.waitForTimeout(300);
console.log('where(now):', (await p.innerText('#gwhere')).replace(/\s+/g,' '));
await p.click('[data-pl="3"]'); await p.waitForTimeout(300);
console.log('where(base):', (await p.innerText('#gwhere')).replace(/\s+/g,' '));
await p.screenshot({path:'/tmp/claude-0/tS-portal.png', fullPage:false});
await p.fill('#gpaste','6413FDFF7FF9'); await p.click('#gload'); await p.waitForTimeout(300);
console.log('where(bountria):', (await p.innerText('#gwhere')).replace(/\s+/g,' '));
await p.fill('#gpaste','1001000AAAAA'); await p.click('#gload'); await p.waitForTimeout(300);
console.log('where(far):', (await p.innerText('#gwhere')).replace(/\s+/g,' '));
await p.click('#gwmap'); await p.waitForTimeout(600); console.log('tab galaxy', await p.isVisible('#p-galaxy')); await p.screenshot({path:'/tmp/claude-0/tS-map.png'});
await p.click('#t-portals'); await p.click('[data-pmap="1"]'); await p.waitForTimeout(500); console.log('info:', (await p.innerText('#ginfo')).slice(0,80).replace(/\s+/g,' '));
console.log('errors', errs); await b.close();})();
